### ISSUE TITLE
PUSH FAILED on 11/25/15, 2:09 PM

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#5] opened 2015-11-28 15:45 UTC
I received this PUSH FAILED email on the aforementioned date:

> Error: Repo createContents error

> Error: Repo createContents error. Error committing to file acid-base-solutions/acid-base-solutions-strings_te.json

> [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]

Assigning @jbphet since it is related to build-server.  Tagging @pixelzoom since it relates to acid-base-solutions.

EDIT: Formatting

**Comment by pixelzoom** [comment] 2015-11-28 17:08
The `[object Object]...` portion of that error message is pretty useless.  A related issue would be to improve the error message.

**Comment by jbphet** [comment] 2015-11-30 21:37
Gathering information on this.  The commit in question seems to have made it into babel, and the timestamp matches that reported in the email message, i.e. 11/25/15, 2:09 PM MST.  See https://github.com/phetsims/babel/commit/f293f542d524e155429f68a1dc40b74146cb37d8.

**Comment by jbphet** [comment] 2015-11-30 21:52
This issue is in the wrong place.  The problem is coming from the translation utility (rosetta), not the build server (perennial).  Moving.

**Comment by jbphet** [comment] 2015-11-30 21:57
This issue has been moved to https://github.com/phetsims/rosetta/issues/105.  Closing this version.

**Closed by jbphet** 2015-11-30 21:57 UTC
