### ISSUE TITLE
Translations missing after maintenance release on 6/22/16

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#23] opened 2016-08-22 16:30 UTC
Phethelp received an email this morning requesting to readd the ar translations for concentration and molecules-and-light to the website.  Inspecting the archived built sim files, it was discovered that the built translations for these two sims are missing from the versions after June 22.  The last version with all of the translations is 1.2.5 for concentration 1.1.5 for molecules-and-light.

**Comment by jbphet** [comment] 2016-08-22 16:47
By looking at the files on Figaro, I can see that for both molecules-and-light and concentration the XML file that contains the list of translations got "reset", meaning that it contained only the English translation, after the publication on Jun 22nd.

**Comment by jbphet** [comment] 2016-08-22 16:49
For the record, the maintenance release that ended up blowing away the existing translation were to add the functionality needed for the BrainPop demo, see https://github.com/phetsims/phet-io/issues/476.

**Comment by jbphet** [comment] 2016-08-22 16:55
One way to resolve this quickly would be to merge the pre-Jun-22 XML file with the latest XML file (since some new translations have come in since Jun 22) and republish from the current branch.  That wouldn't tell us **why** this happened, but it would fix the immediate issue.  I think I'll move forward with this plan, then go back and look through the logs to see if there is something that needs to be fixed within the build server.

In general, I think we need to revisit this approach of using the XML files to track the translations.  Seems like pulling the information out of the DB used by the web site would be better - that would at least assure that what is seen on the web site matches what the build server thinks it needs to build.

**Comment by jbphet** [comment] 2016-08-22 17:33
By the way, are we sure that these two sims are the only ones that were affected?  I just asked Steele to do some checking and make sure that the other HTML5 sims appear to be okay.

**Comment by phet-steele** [comment] 2016-08-22 17:43
I tried one translation from every other simulation and they loaded and ran successfully. The locale tested was more or less random for each.

**Comment by jbphet** [comment] 2016-08-22 18:50
This is now fixed for both Concentration and Molecules and Light.

**Comment by mattpen** [comment] 2016-08-22 18:52
I ran a quick script to test response status codes for all the localized sims in the database.  I only got 404 responses for C and MAL, so I don't think this affecting any other sims.

**Comment by jbphet** [comment] 2016-08-22 19:04
Here is my best educated guess at a root cause: Something went wrong with the bulk deployment process (this happens fairly frequently), and I did the production deployment manually for these sims, and I left off the ```--locales=*``` flag.  This absence of this flag is only a problem if the version of chipper used by the sim is older than Nov 15 2015, and I've verified that this was the case on the 1.1 branch of Molecules and Light and the 1.2 branch of Concentration.  That makes a lot of sense, so I'm fairly confident that this was the issue.  There isn't much that can be done to avoid this in the future other than to remember this flag for all production deployments.

**Comment by mattpen** [comment] 2016-08-22 19:06
I just ran my script again and it returned no 404's for localized sims.

**Comment by jbphet** [comment] 2016-08-22 19:09
Then I think our work here is done.  Closing.

**Comment by pixelzoom** [comment] 2016-08-22 19:13
> There isn't much that can be done to avoid this in the future other than to remember this flag for all production deployments.

There is something else that can be done -- test a few translations after deploying.  Given the state of PhET build tools, I do this as a habit.

**Comment by samreid** [comment] 2016-08-22 20:36
> There is something else that can be done -- test a few translations after deploying. Given the state of PhET build tools, I do this as a habit.

That is a good suggestion, here is my recommended addition to the bulk-maintenance-release-process.md:

```
### 5. Testing

After deploying, the English and at least one non-English simulation should be tested from the website.  You must be logged in to the website so you do not receive a stale cached version of the simulation.
```

@jbphet can you review my recommended addition to the bulk-maintenance-release-process.md and add it if it seems good?

**Comment by jbphet** [comment] 2016-08-22 22:06
Added the suggested text to the bulk-maintenance-release-process.md document with some minor edits.  Closing.

**Closed by jbphet** 2016-08-22 22:06 UTC
