### ISSUE TITLE
Automated maintenance scripts should use the index wrapper location

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#103] opened 2018-08-15 03:22 UTC

**Comment by jonathanolson** [comment] 2018-08-16 19:00
https://github.com/phetsims/chipper/commit/8db0653ee0cbb6ed716fa3b4d4759bcb75d8118a changed the location.

**Comment by zepumph** [comment] 2019-04-19 21:14
Duplicate of https://github.com/phetsims/perennial/issues/114

**Closed by zepumph** 2019-04-19 21:14 UTC
