### ISSUE TITLE
investigate using synchronous system calls

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#37] opened 2017-04-21 21:08 UTC
build-server.js current has what is often referred to as a 'pyramid of doom' (see https://en.wikipedia.org/wiki/Pyramid_of_doom_(programming) caused by a long sequence of asynchronous system calls.  Here is a screenshot of the code:

![pyramid](https://cloud.githubusercontent.com/assets/3082831/25296096/cfa50e06-26a3-11e7-99c9-4a17a5686cb1.PNG)

This is hard to read and maintain, so I started investigating a JavaScript construct called "promises" as an alternative way to handle this.  However, during this investigation, I found that there may be a simpler alternative: `child_process.execSync`.  The code currently uses `child_process.exec`, which is asynchronous and leads to the pyramid, but it may be possible to fix this by simply using a synchronous version of the same call.

I've used up my budgeted time for this sort of investigation for this week, but will pick it up again in a week or two.

**Comment by jonathanolson** [comment] 2017-10-30 20:50
Looks like https://github.com/phetsims/perennial/issues/42 is basically a duplicate of this.

Noted:

> Investigate moving away from callback pyramid of doom. Suggestions for improvement were Async await (@samreid), Promises(@jbphet), and fibers/future(@mattpen).

**Comment by jonathanolson** [comment] 2017-11-29 20:59
Promises + async/await has been amazing for the rest of chipper/perennial. I'll be available to help with this.

**Comment by mattpen** [comment] 2017-11-29 21:06
Changing assignment to myself as @jbphet is focused on changes for rosetta.

**Comment by mattpen** [comment] 2017-12-13 07:31
I've started implementing this as part of the refactor for #56.

**Comment by mattpen** [comment] 2017-12-15 16:28
Using async/await instead of callbacks has been implemented for the entire build-server and is working nicely. Closing.

**Closed by mattpen** 2017-12-15 16:28 UTC
Labels: chipper:2.0
