### ISSUE TITLE
Review build-server for improvements in modularity and async handling

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#42] opened 2017-09-28 17:37 UTC
Investigate moving away from callback pyramid of doom.  Suggestions for improvement were Async await (@samreid), Promises(@jbphet), and fibers/future(@mattpen).

**Comment by jonathanolson** [comment] 2017-10-30 20:50
Duplicate of https://github.com/phetsims/perennial/issues/37, closing.

**Closed by jonathanolson** 2017-10-30 20:50 UTC
Labels: chipper:2.0
