### ISSUE TITLE
Update PhET-iO grunt production comment to assign to @brent-phet instead of @kathy-phet

### ISSUE THREAD

**Issue by brent-phet** [phetsims/perennial#324] opened 2023-06-07 01:08 UTC
https://github.com/phetsims/perennial/blob/9e8f1fcf245427f16953190e8f8155aef0efdbf6/js/grunt/production.js#L224

From `grunt production --branch=1.3 --brands=phet,phet-io`:

> PhET-iO deploys involve a couple of extra steps after production. Please ensure the following are accomplished:
...
> 2. Create an issue in the phet-io repo and assign to @kathy-phet to update the main "PhET-iO Simulations" spreadsheet from this new publication. (https://docs.google.com/spreadsheets/d/18_QNGuVtYtxOEKG9xRBs_PSQpyvzySF1Gk5puR-5Fv4/edit#gid=1881767354)

**Comment by brent-phet** [comment] 2023-06-07 02:02
This is a duplicate to #325 resolved by @pixelzoom. @kathy-phet just mentioned assigning @zepumph but not strictly required.

**Comment by pixelzoom** [comment] 2023-06-07 02:31
There's some confusion here.  

This is not a duplicate of https://github.com/phetsims/perennial/issues/325.  This issue was to update the PhET-iO spreadsheet for GO and GO:Basics publications. https://github.com/phetsims/perennial/issues/325 was to change the `grunt publication` message so that future issues like this would be assigned to @brent-phet.

It also looks like @brent-phet intended to close this issue, but did not.

I see that the PhET-iO spreadsheet was updated, so I will close this issue.

**Closed by pixelzoom** 2023-06-07 02:31 UTC
Labels: priority:4-low
