### ISSUE TITLE
occasional SCP failures when transferring files to spot (dev server)

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#20] opened 2016-04-14 18:42 UTC
We are occasionally seeing errors with the build server when it is transferring a lot of files from the server on which it's running (figaro as of this writing) to the dev server (spot as of this writing).  The errors in the build server log look like this:

> Apr 01 2016 16:16:06 MDT - error: error running command: scp wave-on-a-string_nl.html jblanco@spot.colorado.edu:/htdocs/physics/phet/dev/html/wave-on-a-string/1.1.2-rc.1 in ../wave-o       n-a-string/build. build aborted.

@jonathanolson says that he thinks that this might be due to limitations imposed by CU's IT infrastructure that limit the number of sequential SSH sessions that can be set up, and each one of these SCP requests may be creating a new SSH session.  We may be able to fix this using something where a connection is established and multiple files are transferred.

**Comment by jbphet** [comment] 2016-06-15 18:59
There is a comment in ```build-server.js``` that explains why each file is separately copied instead of using ```scp -r``` to copy the entire directory.  The comment and beginning of the associated function looks like this:

```js
  /**
   * Copy files to spot. This function calls scp once for each file instead of using scp -r. The reason for this is that
   * scp -r will create a new directory called 'build' inside the sim version directory if the version directory already
   * exists.
   * @param callback
   */
  var spotScp = function( callback ) {
    var userAtServer = BUILD_SERVER_CONFIG.devUsername + '@' + BUILD_SERVER_CONFIG.devDeployServer;
    var simVersionDirectory = BUILD_SERVER_CONFIG.devDeployPath + simName + '/' + version;
   .
   .
   .
```

**Comment by jbphet** [comment] 2016-06-15 19:21
I added code to skip the transfer of translations to spot.  This code is a bit of a hack, and we may not want to keep it long term.  We should discuss in the next dev meeting.

**Comment by samreid** [comment] 2016-06-16 13:45
> scp -r will create a new directory called 'build' inside the sim version directory if the version directory already exists.

It sounds like we just need to fix the destination path.

**Comment by samreid** [comment] 2016-06-16 13:50
Or some way to do:

```
cd build
scp -r .
```

**Comment by samreid** [comment] 2016-06-16 18:10
@andrewadare recalled something about leaving or adding the trailing slash for the directory may affect whether the directory itself is transmitted.

**Comment by samreid** [comment] 2016-06-20 14:56
On Thursday, @andrewadare and @samreid recommended that @jbphet investigate further into the root cause of this problem, and @jbphet agreed to do so.

**Comment by mattpen** [comment] 2016-09-22 01:49
This needs to be fixed to proceed with https://github.com/phetsims/chipper/issues/481#issuecomment-248740673.  I'm assigning to myself.

**Comment by mattpen** [comment] 2016-09-22 02:11
If our cwd is `build/` and we run `scp -r * /path/to/simname/version` it should copy everything in a single command and not create a new build directory on spot.  I'm not sure if it will solve the problem of sequential ssh sessions or not.  Perhaps we can use rsync if this does not work?

**Comment by samreid** [comment] 2016-09-22 02:13
I'm hopeful that changing from many scp commands to one will help with this issue.

**Comment by mattpen** [comment] 2016-09-22 03:24
I created branch `phet-io-changes` for this issue.

**Comment by mattpen** [comment] 2016-09-30 20:08
[10:36:15 AM] Jesse Greenberg: I just did a deploy-rc for forces-and-motion-basics and it looks like all translated versions were moved to spot, is this the expected behavior?
[10:36:55 AM] Jesse Greenberg: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.0-rc.2/

The new command mentioned here: https://github.com/phetsims/perennial/issues/20#issuecomment-248793490 seems to be working without errors, although it is now copying all of the translations for rc deploys to spot.  @jbphet Should this be avoided?

**Comment by mattpen** [comment] 2016-10-01 02:10
@jbphet - I removed the translations from being copied in the previous commit.  Please let me know if I should add them back in.

**Comment by jbphet** [comment] 2016-10-04 16:34
I think it is best to omit the translations on spot.  They take up a lot of room, and at least in my personal experience I've never had the need to access a translated version of a sim from the dev server.

I inspected the code change, and have a couple of notes:
+ With the changes in the ```spotScp``` function, the header comment is now incorrect.  This should be updated, assuming that the issue described in the header has truly been corrected.
+ There is an used var ```files```.

We should make sure this is tested before merging into master and deploying to the build-server.

Back to @mattpen for the next steps.

**Comment by mattpen** [comment] 2016-10-04 17:47
The suggested changes have been applied and I restarted the build-server.  I'll check the next time someone does an RC deploy to make sure that it was successful.

**Comment by mattpen** [comment] 2016-10-04 17:48
Several RC deploys of phet-io brands have been deployed successfully after the change, RC deploys for phet brand are remaining to be tested

**Comment by mattpen** [comment] 2016-10-22 03:41
An RC deploy was tested today for faradays law as part of phetsims/chipper#507.  This is complete.

**Closed by mattpen** 2016-10-22 03:41 UTC
