### ISSUE TITLE
Investigate build failures with message "Error: Request failed with status code 50x"

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#252] opened 2021-11-29 20:39 UTC
We've been getting a number of build failure emails lately that contain the message `Error: Request failed with status code 50x` where the x is either 0, 2, or 3.  Here is an example from Sun 11/28/2021 3:05 PM:

<details>

```
Build failure: Error: Build aborted, Error: Error: Request failed with status code 500. Sim = forces-and-motion-basics Version = 2.3.18 Brands = phet Locales = yo Shas = {"comment":"# forces-and-motion-basics 2.3.18 Thu Nov 18 2021 18:15:21 GMT-0700 (Mountain Standard Time)","assert":{"sha":"928741cfc8fe804334d5b35292140314511f8678","branch":"HEAD"},"axon":{"sha":"49396a5cd082fb2e9471748f553aef458237191a","branch":"HEAD"},"brand":{"sha":"8a5077a589f3f4c5b2aaa6f77f6f4fbdd87ea162","branch":"HEAD"},"chipper":{"sha":"ac8c0147727421c3688ffe3f7bd4470be053eadf","branch":"HEAD"},"dot":{"sha":"db33a2c7fca14980bccd7d9517839c5b8ae7a9ee","branch":"HEAD"},"forces-and-motion-basics":{"sha":"e263ceb701b58ff7165df821d8600ab43691ad7d","branch":"HEAD"},"joist":{"sha":"4343d8ab8d9b3ca0d9efccc3978d93a017fdeb33","branch":"HEAD"},"kite":{"sha":"dc5c4382bce034652a4e0bae6c739ba8284b2558","branch":"HEAD"},"phet-core":{"sha":"283b47e7f0a4d4066db46731a8bfc32f70811545","branch":"HEAD"},"phetcommon":{"sha":"276441fcc00a4588f42b40a90e15e103e3e83498","branch":"HEAD"},"phetmarks":{"sha":"748865c3dadc35197b9c215e2f8a87fb451f92ac","branch":"HEAD"},"query-string-machine":{"sha":"c74e454ec68033a9546b8181d4d962eb8ceef81f","branch":"HEAD"},"scenery":{"sha":"369b81f41ec72bc02fa5ba34c9c61e40bf11773a","branch":"HEAD"},"scenery-phet":{"sha":"313462efc6d1c89916e847565180bc7a302d4056","branch":"HEAD"},"sherpa":{"sha":"dba01386dd884865c2111c0b5c63f31a4cdfbefb","branch":"HEAD"},"sun":{"sha":"96c223b3fb271992069088e4d48019b141c9191c","branch":"HEAD"},"tandem":{"sha":"e6a58f1e657fa6ce5b80d34aa6a05e2adc214380","branch":"HEAD"},"vibe":{"sha":"3981024e7ed3299cf57fc92f1e4b425a4c335e08","branch":"HEAD"}}
```

</details>

I checked whether this particular build was actually published, and it appears that it was, so this error seems like something after the actual build and publication step has been completed.

I looked through the build server log and noticed that in this particular instance, a request for a build was received immediately after this one, and the error seemed to occur during _that_ build (which was for fractions-intro), so it may be a problem in the queuing and error notification mechanisms.

I also looked through the log for rosetta (the translation utility), and saw no errors there.

I have several other failure notification emails, but it doesn't seem worthwhile to put them into this ticket, since @mattpen probably has them too.  @mattpen - please let me know if you need any more information from me on this.

**Comment by jbphet** [comment] 2021-11-29 20:41
By the way, this seems to me like a different problem than #251, which is another open issue related to build failures.  That's why I opened a new issue.

**Comment by mattpen** [comment] 2021-12-01 16:46
I'm planning to evaluate this and #251 tomorrow morning.

**Comment by mattpen** [comment] 2021-12-02 16:54
It looks like there are five recent failures due to a 500 response from tomcat. The 500 response appears to be false, as I checked the logs and verified that each of these requests completed successfully. However, the error response would trigger the build to abort and anything after the notifyServer step would be skipped. It looks like this means that each of these builds would have skipped the addTranslator step, so there are likely missing build credits.

I think 2 actions are needed.

We need to add the translation credits to the database. @oliver-phet - can you identify the yo translator so I can fabricate these?

We should make sure that this false error doesn't trigger in the future. There is no record of the error in the logs, so I believe it was probably a timeout triggered since the request took more than 60 seconds to complete. I'll change the sync step to work asycronously, so that it returns a 202 Accepted response which indicates that it was a well formed request but that the response will be completed at some other time. I'll also add some more logging to hopefully get a better idea of what the error is if this solution doesn't work.

**Comment by oliver-phet** [comment] 2021-12-02 18:41
> 1. We need to add the translation credits to the database. @oliver-phet - can you identify the yo translator so I can fabricate these?

I'll send you a dm with the (likely) translator id. But it should be recognized that some locales have _many_ trusted translators so it would not be easy to identify the translator that submitted. Also, it is currently possible for _any_ trusted translator (or PhET team member) to submit a _yo translation.

**Comment by mattpen** [comment] 2021-12-02 18:46
@jbphet - is the translator for these logged in rosetta? It would be ideal to confirm that we are crediting the correct translator.

date: Nov 18 13:07, locale: yo, sim: area-model-introduction
date: Nov 18 13:38, locale: yo, sim: balancing-act
date: Nov 23 12:07, locale: yo, sim: balloons-and-static-electricity
date: Nov 28 15:02, locale: yo, sim: forces-and-motion-basics
date: Nov 30 10:01, locale: yo, sim: wave-on-a-string

**Comment by oliver-phet** [comment] 2021-12-02 18:52
@mattpen userid is logged in babel, if that helps: https://github.com/phetsims/babel/blob/master/area-model-introduction/area-model-introduction-strings_yo.json

**Comment by mattpen** [comment] 2021-12-02 19:02
Yep, that works, thanks!

**Comment by mattpen** [comment] 2021-12-02 21:30
I deployed the changes and successfully tested a yo translation of chains.  I also confirmed that all the appropriate translation credits were applied (perhaps the translator had translated previous versions or submitted multiple times). This appears to be fixed, closing.

**Closed by mattpen** 2021-12-02 21:30 UTC
