### ISSUE TITLE
dependencies not being copied to spot

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#29] opened 2016-12-14 20:30 UTC
@samreid noticed that the `dependencies.json` file is not being copied to spot for RC deployments, possibly production deployments too.  I took a look through the code and the history, and I think that this commit may be implicated:

https://github.com/phetsims/perennial/commit/da982bde0f902abd7ef3ab2921f57e5425ccb4c3

It was an attempt at a solution to #20.

This change was probably not quite right, and needs to also make sure that the dependencies files are moved.  Assigning to @mattpen.

**Comment by jbphet** [comment] 2016-12-14 22:16
@mattpen - it it is confirmed that this is the problem, can you update https://github.com/phetsims/states-of-matter/issues/196 - basically just close it and note that the work on this will be tracked here.

**Comment by mattpen** [comment] 2016-12-16 06:13
@jbphet - It looks like before the scp command was excluding any .html file that was not english, but included other files.  I erroneously translated this into only selecting the english html, which started excluding all non-html files.  I'll take a look tomorrow into how to fix it.

**Comment by mattpen** [comment] 2017-01-19 04:48
@jbphet - It looks like this should be fixed now.  I uploaded the changes to phet-server, did a redeploy of chains, and verified that dependencies.json was copied along with it.  

The root cause was that the original change I made only copied the English sim.  The command now copies the english sim and any other files that do not end with `.html`.

Sending back to you to review the commit and close if everything looks ok.

**Comment by jbphet** [comment] 2017-01-27 17:48
I just reviewed that code and have a few comments.  Also, we discussed this a bit during yesterday's developer meeting, so there may be a bit more work to be done as a result of what we concluded then.

Comments:
+ It would be good for the comments to explain why we transfer all files for phet-io brand and not for phet brand.  I believe this is because phet-io specifically does *not* produce any translations.
+ There is a commented out line of code, currently at line 619.  Can this be removed?
+ If the brand is not phet-io, there are two transfers done, and it looks like they are both initiated immediately, i.e. the first does not wait for the second to complete.  This is different from how it is done if the brand is phet-io.  It wasn't obvious to me why these are done differently.  I'd recommend doing them sequentially or documenting why it is unnecessary.
+ We should add some logging to this code so that can more easily see in the build server if things go awry.  First, it should log what it's trying to do (e.g. transferring files to dev server, brand = phet) and should log a message on success or failure.

That's it for now.  Back to @mattpen for his response, and I'm happy to review any further changes.

**Comment by jessegreenberg** [comment] 2017-01-30 18:35
After a recent RC deploy of gravity-force-lab 2.1.0-rc.1 I received this build-server error:

```json
Build failed with error: error running command find . -type f ! ( -iname '*.html' ) -exec scp {} jblanco@spot.colorado.edu:/htdocs/physics/phet/dev/html/gravity-force-lab/2.1.0-rc.1 ;: Error: Command failed: /bin/sh -c find . -type f ! ( -iname '*.html' ) -exec scp {} jblanco@spot.colorado.edu:/htdocs/physics/phet/dev/html/gravity-force-lab/2.1.0-rc.1 ;
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `find . -type f ! ( -iname '*.html' ) -exec scp {} jblanco@spot.colorado.edu:/htdocs/physics/phet/dev/html/gravity-force-lab/2.1.0-rc.1 ;'
. Sim = gravity-force-lab Version = 2.1.0-rc.1 Locales = * Shas = {
  "comment": "# gravity-force-lab 2.1.0-rc.1 Mon Jan 30 2017 10:56:27 GMT-0700 (Mountain Standard Time)",
  "assert": {
    "sha": "a707328cc11048787a807714496af23e0bd25be1",
    "branch": "master"
  },
  "axon": {
    "sha": "1cf1028125aff542d863c6f40ecd3ee03ceaef74",
    "branch": "master"
  },
  "brand": {
    "sha": "0be722ee4e70a5689a86a246e86651f1b844574d",
    "branch": "master"
  },
  "chipper": {
    "sha": "f4cd39bfd3865b29e8f87da62e39f24d1fb9b335",
    "branch": "master"
  },
  "dot": {
    "sha": "75380061a901393db079c24d019e0eb03abe68c2",
    "branch": "master"
  },
  "gravity-force-lab": {
    "sha": "021d9ff06fa7418411b3d8db3a01997313136acc",
    "branch": "2.1"
  },
  "joist": {
    "sha": "d15e6fab2a00ab2b697cb56f65ed2902bff4630e",
    "branch": "master"
  },
  "kite": {
    "sha": "6059ebb0210f3aeeb4b6863445ed94245e54fef1",
    "branch": "master"
  },
  "phet-core": {
    "sha": "84747dff066a54fc6f6220aabd2b1a2195ebb6e6",
    "branch": "master"
  },
  "phetcommon": {
    "sha": "1cb33196c7b03661a71e82d189e66d95c92cc061",
    "branch": "master"
  },
  "query-string-machine": {
    "sha": "d8a4ff18a12aff003e4896213c1dfed5a79c1a30",
    "branch": "master"
  },
  "scenery": {
    "sha": "550df01a1bc6a51bfbfe9c09f65ae8fc802539a5",
    "branch": "master"
  },
  "scenery-phet": {
    "sha": "b04d8086939d00a810ba53f53e8f68f5671251ae",
    "branch": "master"
  },
  "sherpa": {
    "sha": "785a536c157f34ab1af195b0d40cff3fff023a2b",
    "branch": "master"
  },
  "sun": {
    "sha": "d0708aa57511473268e50fc1fd7c0f6fca6d35d5",
    "branch": "master"
  },
  "tandem": {
    "sha": "d9c124e5a7d30ac8013874e932122085f3477da9",
    "branch": "master"
  }
}
```

It looks like the error might be related to this issue since the problem is related to the scp step.  The build directory was copied correctly to spot even though I received this error (though dependencies.json was not copied over).

**Comment by mattpen** [comment] 2017-01-30 20:30
I'm not sure why this would have failed, as `find . -type f ! ( -iname '*.html' )` runs without error on phet-server, even running it as phet-admin.

**Comment by jbphet** [comment] 2017-02-10 16:41
Saw two more emails this morn that seem to indicate an issue with copying files to spot.  Below is the content of one of them:

```
Build failed with error: error running command find . -type f ! ( -iname '*.html' ) -exec scp {} jblanco@spot.colorado.edu:/htdocs/physics/phet/dev/html/bending-light/1.1.4-rc.2 ;: Error: Command failed: /bin/sh -c find . -type f ! ( -iname '*.html' ) -exec scp {} jblanco@spot.colorado.edu:/htdocs/physics/phet/dev/html/bending-light/1.1.4-rc.2 ;
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `find . -type f ! ( -iname '*.html' ) -exec scp {} jblanco@spot.colorado.edu:/htdocs/physics/phet/dev/html/bending-light/1.1.4-rc.2 ;'
 Sim = bending-light Version = 1.1.4-rc.2 Locales = * Shas = {
  "comment": "# bending-light 1.1.4-rc.2 Thu Feb 09 2017 21:52:11 GMT-0700 (MST)",
  "assert": {
    "sha": "7d27130a4d27da15aa7f8a21bbfb9245288c1b44",
    "branch": "HEAD"
  },
  "axon": {
    "sha": "1fd9183228d023c668b50d2230f13c03b6963a96",
    "branch": "HEAD"
  },
  "bending-light": {
    "sha": "19508466bfa554c5339be595d5ec8ba432fb9b62",
    "branch": "1.1"
  },
  "brand": {
    "sha": "f0b1f7da85f87b9626562bea7fe69197fa81f05f",
    "branch": "HEAD"
  },
  "chipper": {
    "sha": "136b1d30c9cb95165fd05dbcef0e6dfc1704c576",
    "branch": "HEAD"
  },
  "dot": {
    "sha": "6e8a26f2976e70a018b205206d20049b35972cc3",
    "branch": "HEAD"
  },
  "joist": {
    "sha": "ab5582ab6c8d87abb8bcdf947ef8144eb96ea7b6",
    "branch": "HEAD"
  },
  "kite": {
    "sha": "88f0c3a051a24f71a6465641badeccab1246820a",
    "branch": "HEAD"
  },
  "phet-core": {
    "sha": "c48bf32035dc5a4ed092ad611012fcbdeb5c6351",
    "branch": "HEAD"
  },
  "phetcommon": {
    "sha": "e77d2353abefa38498cc971d856620f3679fb3ba",
    "branch": "HEAD"
  },
  "scenery": {
    "sha": "0ab22ac3398ee77a64b502c451c7b0bea3ddf83d",
    "branch": "HEAD"
  },
  "scenery-phet": {
    "sha": "04cec21659b983e87e24de2935ff4860a64923f0",
    "branch": "HEAD"
  },
  "sherpa": {
    "sha": "5ddfccd4d439c8ceeb4739de4c790d2e75cb7ef7",
    "branch": "HEAD"
  },
  "sun": {
    "sha": "061f2ea9ad6f26fd063ff9afedca9f77e5064747",
    "branch": "HEAD"
  },
  "tandem": {
    "sha": "43ebdfb3f57308563c7735b83ec9b4122eebf0a8",
    "branch": "HEAD"
  }
}
```

**Comment by samreid** [comment] 2017-02-10 17:05
Correct, the dependencies.json is not where it should be:

http://www.colorado.edu/physics/phet/dev/html/bending-light/1.1.4-rc.2/

**Comment by samreid** [comment] 2017-02-10 17:06
Bumping to high priority, the dependencies.jsons are essential.  @mattpen is this something you can look into further?

**Comment by jessegreenberg** [comment] 2017-02-14 18:42
I think I hit this again with an RC deploy, here is the error message and dependencies.json:

```json
Build failed with error: error running command find . -type f ! ( -iname '*.html' ) -exec scp {} jblanco@spot.colorado.edu:/htdocs/physics/phet/dev/html/gravity-and-orbits/1.1.0-rc.1 ;: Error: Command failed: /bin/sh -c find . -type f ! ( -iname '*.html' ) -exec scp {} jblanco@spot.colorado.edu:/htdocs/physics/phet/dev/html/gravity-and-orbits/1.1.0-rc.1 ;
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `find . -type f ! ( -iname '*.html' ) -exec scp {} jblanco@spot.colorado.edu:/htdocs/physics/phet/dev/html/gravity-and-orbits/1.1.0-rc.1 ;'
. Sim = gravity-and-orbits Version = 1.1.0-rc.1 Locales = * Shas = {
  "comment": "# gravity-and-orbits 1.1.0-rc.1 Tue Feb 14 2017 11:28:25 GMT-0700 (Mountain Standard Time)",
  "assert": {
    "sha": "a707328cc11048787a807714496af23e0bd25be1",
    "branch": "master"
  },
  "axon": {
    "sha": "03e252e3f7252c9853e6080ab9b2cf5369f50580",
    "branch": "master"
  },
  "brand": {
    "sha": "0be722ee4e70a5689a86a246e86651f1b844574d",
    "branch": "master"
  },
  "chipper": {
    "sha": "72a9db00c170ce439e4207e71639823e9cb5f3ef",
    "branch": "master"
  },
  "dot": {
    "sha": "9b3b950fd8f8a5c1efcef537ea066db7b23173d6",
    "branch": "master"
  },
  "gravity-and-orbits": {
    "sha": "94a8f15d8b01ab10e56df47b96cf0693a15ad620",
    "branch": "1.1"
  },
  "joist": {
    "sha": "09c7e0f2e9b8beb74d3f415963a3665570f4edb2",
    "branch": "master"
  },
  "kite": {
    "sha": "f4c67cff6e24693f66b58fcea16069be3dbd8e88",
    "branch": "master"
  },
  "phet-core": {
    "sha": "c5c6c2a8273b9bd3f3bcb4ddfbcf24058b58954a",
    "branch": "master"
  },
  "phetcommon": {
    "sha": "d128c5fb2ffcdafe82bb8b26096cff3790ddf872",
    "branch": "master"
  },
  "query-string-machine": {
    "sha": "d8a4ff18a12aff003e4896213c1dfed5a79c1a30",
    "branch": "master"
  },
  "scenery": {
    "sha": "f94936d1ceafe2abf09ee7235b6f6bc0ba07639d",
    "branch": "master"
  },
  "scenery-phet": {
    "sha": "9233aff82ac8e9366d444e72d40603e59a261493",
    "branch": "master"
  },
  "sherpa": {
    "sha": "985665662c9862d5b38583a715896029b46feb44",
    "branch": "master"
  },
  "sun": {
    "sha": "9c5de75906c0fa05d8535b83d394bc41374f5851",
    "branch": "master"
  },
  "tandem": {
    "sha": "4ac1125441b04a890088f9704314879aba5dead0",
    "branch": "master"
  }
}
```

**Comment by mattpen** [comment] 2017-02-14 19:03
I think I'm missing some double escapes in the strings, although I'm not sure why.

i.e.:

```
find . -type f ! ( -iname '*.html' )
bash: syntax error near unexpected token `('
```

```
$ find . -type f ! \( -iname \'*.html\' \)
./dependencies.json
./.htaccess
./acid-base-solutions-600.png
./acid-base-solutions.xml
./changes.txt
./acid-base-solutions_string-map.json
./acid-base-solutions_en.html
./acid-base-solutions-128.png
```

**Comment by mattpen** [comment] 2017-03-09 17:51
No one has noticed missing dependencies since this was deployed.  Closing.

**Closed by mattpen** 2017-03-09 17:51 UTC
Labels: priority:2-high
