### ISSUE TITLE
Puppeteer Timeout when parsing for screen names during

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#290] opened 2022-12-06 18:22 UTC
This is occurring on the build-server in production ever since we upgraded to 19 over in https://github.com/phetsims/perennial/issues/268.

@jonathanolson recently that my-solar-system failed yesterday. The build-server logs looked like:

```
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]: error: Could not parse screen names from sim: TimeoutError: Waiting failed: 30000ms exceeded
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]: error: Stop status: waitForFunction phet
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]: error: TimeoutError: Waiting failed: 30000ms exceeded
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]:     at Timeout.<anonymous> (/data/share/phet/build-server/perennial/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:64:32)
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]:     at listOnTimeout (node:internal/timers:559:17)
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]:     at processTimers (node:internal/timers:502:7)
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]: error: BUILD ABORTED! TimeoutError: Waiting failed: 30000ms exceeded
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]: error: TimeoutError: Waiting failed: 30000ms exceeded
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]:     at Timeout.<anonymous> (/data/share/phet/build-server/perennial/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:64:32)
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]:     at listOnTimeout (node:internal/timers:559:17)
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]:     at processTimers (node:internal/timers:502:7)
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]: info: build aborted: checking out master for every repo in case build shas are still checked out
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]: debug: Running grunt checkout-master-all from .
Dec 05 15:00:32 phet-server2.int.colorado.edu build-server[3140307]: debug: stdout: Running "checkout-master-all" task
Dec 05 15:00:33 phet-server2.int.colorado.edu build-server[3140307]: debug: stdout: error in git checkout master for repo number-compare
Dec 05 15:00:33 phet-server2.int.colorado.edu build-server[3140307]: debug: stdout:
Dec 05 15:00:33 phet-server2.int.colorado.edu build-server[3140307]: debug: stdout: Done.
Dec 05 15:00:33 phet-server2.int.colorado.edu build-server[3140307]: debug: Command grunt finished. Output is below.
Dec 05 15:00:33 phet-server2.int.colorado.edu build-server[3140307]: debug: stderr is empty.
Dec 05 15:00:33 phet-server2.int.colorado.edu build-server[3140307]: debug: stdout: Running "checkout-master-all" task

```

tagging @mattpen.

The first thing I'm going to try is to load parseScreenNames locally. It seems to be the only puppeteer usage that isn't using puppeteerLoad, so perhaps refactoring to that could solve things. I'm just guessing though.

**Comment by mattpen** [comment] 2022-12-06 18:34
This is a duplicate of https://github.com/phetsims/perennial/issues/273

**Closed by mattpen** 2022-12-06 18:34 UTC
Labels: priority:2-high
