### ISSUE TITLE
why so many devDependencies?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#32] opened 2017-02-03 22:59 UTC
According to its README.md, perennial is "Maintenance tools that won't change with different versions of chipper checked out".  It consists of 5 .js files.  

(1) Why does it have 17 devDependencies in package.json?

(2) Does it really need to use lodash? (See https://github.com/phetsims/sherpa/issues/58#issuecomment-277384022.)

**Comment by jonathanolson** [comment] 2017-02-03 23:56
> (1) Why does it have 17 devDependencies in package.json?

Build-server uses most of those, although there are some possibly unused entries:

- passwd-user
- pg (pg-query is used, does it automatically use pg?)
- express-dot (possibly loaded dynamically, probably for templates)

> (2) Does it really need to use lodash? (See phetsims/sherpa#58 (comment).)

I don't see what the problem is. If depending on Lodash is problematic, removing its usage from sims is more difficult is.

If overall having lots of dependencies is a problem, I'd suggest we start with sim dependencies (which takes up 3.5GB of space for all simulations).

**Comment by pixelzoom** [comment] 2017-02-04 00:16
@jonathanolson said:
> I don't see what the problem is. If depending on Lodash is problematic, removing its usage from sims is more difficult is.

I'm not suggesting removing it from sims.  I'm just wondering if it's worth keeping an old version of lodash around for the small number of usages (8, some dubious) in perennial.

> If overall having lots of dependencies is a problem, I'd suggest we start with sim dependencies (which takes up 3.5GB of space for all simulations).

Space is not the point. The point is that perennial is code that is not supposed to change. And that means that it's dependencies must also be pinned.

**Comment by jonathanolson** [comment] 2017-02-04 00:20
> I'm not suggesting removing it from sims. I'm just wondering if it's worth keeping an old version of lodash around for the small number of usages (8, some dubious) in perennial.

We can bump the version and inspect the usages manually (I saw one _.contains that will need to change in my maintenance release code). I bumped to lodash@^4.0.0 in Yotta the other day.

> Space is not the point. The point is that perennial is code that is not supposed to change. And that means that it's dependencies must also be pinned.

I'd like to clarify that it is fine for it to change, but it should always be run from master (checkout-shas should never roll it back to an old version, that's why we have checkout-sha like stuff there).

**Comment by samreid** [comment] 2017-02-09 17:20
I think the main points to focus on for this issue are: (1) removing unused dependencies and (2) making sure the dependencies don't accidentally change version.

**Comment by jbphet** [comment] 2017-02-09 19:20
I'll take a look and determine which dependencies are unused and will remove them from the file.  Also, @mattpen says that the pg packages shouldn't be used, so if they are a separate issue should be logged.

**Comment by jbphet** [comment] 2017-02-15 20:11
Looking through the code, it appears that the following packages in the dependencies file are unused in the code:

+ `express-dot
+ `pg`
+ `passwd-user`

Also, the package `pg-query` appears to be used in the code, but only to set up an SQL query that is actually never used.  I've logged a separate issue for this, see #33, but I believe that this dependency will ultimately be removed too.

**Comment by jbphet** [comment] 2017-02-15 20:34
I committed changes to remove the three packages listed above, then in a separate commit removed the code that used `pg-query` and then removed that dependency as well.  I then tested on ox-dev by pulling, doing npm prune, npm update, and a restart of the build server and made sure it started okay.  I think did a test build by submitting a changed translation for the 'chains' sim.  Everything seemed to work time.  Assigning to @mattpen to review the changes and do any additional regression testing he can think of.  If everything looks good, we should make these changes live on the phet-server before closing the issue.

**Comment by mattpen** [comment] 2017-02-16 05:38
@jbphet - The changes look good to me, I think its ready for deploy to phet-server.

**Comment by jbphet** [comment] 2017-02-16 16:43
I'll give everyone a heads up in the developer meeting and then will pull this and restart the server.

**Comment by samreid** [comment] 2017-02-22 17:35
@jbphet gave everyone a heads up last developer meeting.  Re-label for developer meeting if there is anything else to discuss.

**Comment by pixelzoom** [comment] 2017-02-22 17:53
@jbphet Is there anything left to discuss here? Or can this be closed?

**Comment by jbphet** [comment] 2017-02-23 16:18
I pulled the changes onto the server, restarted so that they would take effect, and did a test build.  Everything looked good.  I haven't heard of any problems with building, so I think this can be safely closed.

**Closed by jbphet** 2017-02-23 16:18 UTC
