### ISSUE TITLE
During maintenance process, fatal: Unable to create 'acid-base-solutions/.git/index.lock': File exists.

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#284] opened 2022-09-29 15:35 UTC
From https://github.com/phetsims/perennial/issues/283, @mattpen and I saw git lock problems around creating the README file.  Note this problem will be rare after #283 is fixed, but we thought we should mention it.

```
Deployed: https://phet.colorado.edu/sims/html/acid-base-solutions/latest/acid-base-solutions_en.html
Please wait for the build-server to complete the deployment, and then test!
After testing, let the simulation lead know it has been deployed, so they can edit metadata on the website
Updating master README
>> Detected failure during deploy, reverting to master
Maintenance task failed:
Error: Failure with production deploy for acid-base-solutions to 1.2: Error: git checkout master in ../acid-base-solutions failed with exit code 128
stderr:
fatal: Unable to create '/Users/samreid/apache-document-root/main/acid-base-solutions/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

    at Function.deployProduction (/Users/samreid/apache-document-root/main/perennial/js/common/Maintenance.js:900:17)
Full Error details:
{}

```

**Comment by jonathanolson** [comment] 2022-10-06 17:00
Is this something where we were trying to concurrently run multiple copies of git?

**Comment by samreid** [comment] 2022-10-06 22:57
I'm not sure, @mattpen is that possible?

**Comment by mattpen** [comment] 2022-10-07 02:54
I think this process was running on your machine Sam.  Did you have a git dialog open in webstorm while you were running the deploy perhaps? Or a separate terminal with a git operation in progress? This was not a problem with the server side process.

**Comment by samreid** [comment] 2022-10-07 03:02
I'm not aware of anything that was running concurrently, but maybe a process had failed silently somewhere? Want to close this issue and come back to it if it recurs?

**Comment by mattpen** [comment] 2022-10-07 14:07
It seems difficult to reproduce this and low consequence if it reoccurs. Closing sounds appropriate.

**Comment by marlitas** [comment] 2022-11-16 16:28
This happened again in Mean Share and Balance. https://github.com/phetsims/mean-share-and-balance/issues/127

**Comment by mattpen** [comment] 2022-11-16 17:27
This looks like there are some race conditions for git operations in the `grunt production` task AFTER it makes the http call to the build-server.  I did a quick glance at [`production.js`](https://github.com/phetsims/perennial/blob/7858954fbcc2ea455173ebd1f8aef77c1a1c79b2/js/grunt/production.js#L201-L210) - my guess is that the first line in that snippet ( is returning a sucessful Promise before the git commands that run in [`generateREADME.js`](https://github.com/phetsims/chipper/blob/16b7f41994f01a0a028a1fa4e2cac2f22c243b0d/js/grunt/generateREADME.js) actually complete.  Seems like it would be good to just import `generateREADME()` and call it directly rather than calling `await execute( gruntCommand, [ 'published-README' ],...`, but that would introduce a dependency on chipper in perennial which is no good.  I'm not sure if generateREADME.js could be moved to perennial, or if there is a better solution.  As this problem is very transient it will be difficult to even confirm that the problem I described is truly the root cause.

This is really outside of my wheelhouse, I own the build-server code in perennial - not the grunt tasks.  `production.js` was written by @jonathanolson and `generateREADME.js` was written by @pixelzoom. Can either of you help?

**Comment by pixelzoom** [comment] 2022-11-16 22:51
Sorry, this is also outside my wheelhouse.  I wrote generateREADME.js 7+ years ago, as a standalone grunt task, and I haven't touched it since.  And I have no familiarity with the current incarnation of the build-server, or how it uses generateREADME.js.

**Comment by mattpen** [comment] 2022-11-17 16:12
>  I have no familiarity with the current incarnation of the build-server, or how it uses generateREADME.js.

Just to clarify, the build-server does not use generateREADME.js, this is used by the `grunt production` task on the developer's machine.

**Comment by jonathanolson** [comment] 2022-12-12 23:53
> Seems like it would be good to just import generateREADME() and call it directly rather than calling await execute( gruntCommand, [ 'published-README' ],..., but that would introduce a dependency on chipper in perennial which is no good.

We're potentially calling very old versions of the chipper's published-README, so we can't import it from perennial.

**Comment by jonathanolson** [comment] 2022-12-12 23:53
This is causing a lot of issues trying to push out production deployments, investigating.

**Comment by jonathanolson** [comment] 2022-12-13 00:12
It looks like we're not missing `await`, executes are running serially for the entire duration.

**Comment by jonathanolson** [comment] 2022-12-13 02:31
NOTES for future tracking down of file accesses and processes on macOS:

strace isn't available on macOS, but a combination of the following helped:

1. Temporarily open restore mode (M1 mac hold down power button longer on startup to see options, open terminal), `csrutil disable`
2. `sudo newproc.d` helped track down created processes (showed the parent process and PID)
3. `sudo opensnoop -a -c -g -s -t` helped track down file accesses where PID was present (confirmed a PID that we didn't launch directly)
4. `fs_usage -w -f filesys` helped track down thread IDs and processes that were hitting the files (but gave only thread IDs). Gives more fine-grained view on the system calls.
5. `console.log( process.pid )` gave us process IDs to refer to from the other tools
6. Tracking start/stop of things called by `execute()` to make sure there were no overlaps.

**Comment by jonathanolson** [comment] 2022-12-13 17:24
Patches applied above.

**Comment by jonathanolson** [comment] 2022-12-20 22:31
Deployed, closing.

**Closed by jonathanolson** 2022-12-20 22:31 UTC
Labels: dev:maintenance-release
