### ISSUE TITLE
status.sh doesn't stop when it encounters errors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#43] opened 2017-10-14 13:30 UTC
Encountered while attempting to publish a maintenance release in https://github.com/phetsims/unit-rates/issues/203#issuecomment-336634284.

'status.sh' (and any other piece of production code, for that matter) should stop when it encounters fatal errors.

Example:

```
% status.sh
....
chipperfatal: ambiguous argument 'origin/phetioAPIDocs...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
                                   2d1b574e80bcf70cbc1ae7ccda6289a51a98875b/Users/cmalley/PhET/GitHub/chipper/bin/status.sh: line 69: [: : integer expression expected
/Users/cmalley/PhET/GitHub/chipper/bin/status.sh: line 73: [: : integer expression expected

...

scenery-phetfatal: ambiguous argument 'origin/dag-movable-drag-handler': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
                                   6213dc27544de739f31722d59f1a756e20ca03fb/Users/cmalley/PhET/GitHub/chipper/bin/status.sh: line 69: [: : integer expression expected
/Users/cmalley/PhET/GitHub/chipper/bin/status.sh: line 73: [: : integer expression expected
...
%
```

These "fatal" error were buried way back in the output, so they took me awhile to notice. 

Assigning to @ariel-phet to prioritize and assign.  Since this is in perennial, it is unrelated to "chipper 2.0".  @jonathanolson is the author of status.sh.

**Comment by ariel-phet** [comment] 2017-10-16 18:02
@jonathanolson can you let me know how long this should take to fix? Probably a reasonably high priority if not a huge time investment.

**Comment by jonathanolson** [comment] 2017-10-16 19:53
The way I know to handle this is to add something like:
```sh
if [ $? != 0 ]; then
  echo "{{X command}} failed"
  exit 1
fi
```
for every external command run (this is how we detect errors in smithers backup scripts, but we mail out the failure message).

@pixelzoom, does this sound like a good approach? (If yes, I will add it).

> These "fatal" error were buried way back in the output, so they took me awhile to notice.

Not sure if it's helpful, but I generally run status.sh, switch windows to something else to wait, and then when I think it's done I'll scroll back through the entire thing. Maybe it would be beneficial for it to ignore printing "nominal" lines, i.e. where it shows "master" in green right now. Would that be preferred?

**Comment by pixelzoom** [comment] 2017-10-18 17:59
> Maybe it would be beneficial for it to ignore printing "nominal" lines, i.e. where it shows "master" in green right now. Would that be preferred?

I don't think so. There's something reassuring about seeing the "green" line :)

Perhaps before we make a change to status.sh, we should determine what was causing the failures noted above?

**Comment by jonathanolson** [comment] 2017-10-23 17:36
> Perhaps before we make a change to status.sh, we should determine what was causing the failures noted above?

Sure. I don't believe I've had it error out before. Is there a way I can reproduce the failure you experienced above?

**Comment by pixelzoom** [comment] 2017-10-23 17:41
To reproduce:

```
cd unit-rates
git checkout 1.0
cd perennial
grunt checkout-shas --repo=unit-rates
status.sh
```

**Comment by jonathanolson** [comment] 2017-10-23 18:05
So, this was already fixed in master. (Fun story, I fixed it on the checked-out SHA, and it was apparently byte-for-byte identical to latest master!)

But because status.sh is in chipper (old version gets checked out) instead of perennial (where it probably should live), we'd have to patch our release branches to get this to work after checkouts.

Thoughts?

**Comment by pixelzoom** [comment] 2017-10-23 18:08
Punt for now, move status.sh to perennial in chipper 2.0?

**Comment by jonathanolson** [comment] 2017-10-23 18:17
> Punt for now, move status.sh to perennial in chipper 2.0?

Sounds good.

**Comment by jonathanolson** [comment] 2017-12-05 07:04
This was moved to perennial (so should be solved), closing.

**Closed by jonathanolson** 2017-12-05 07:04 UTC
Labels: chipper:2.0, type:bug
